### ISSUE TITLE
Unable to fetch Model

### ISSUE THREAD

**Issue by binguliki** [deepankarvarma/Monkeypox-Skin-Lesion-Detection-OpenCV-TensorFlow-Keras#1]
@deepankarvarma Hey bro👋 , I wanted to use your model for research purpose but i'm not able to fetch the model through LFS link as your bandwidth is less . 
Can you please provide google drive link for the model so that i can use it.

**Comment by deepankarvarma** [comment]
Send me your email id, i will share the download link

**Comment by binguliki** [comment]
okay bro
lbinguma@gitam.in

you can send it at this mail.

**Comment by deepankarvarma** [comment]
Check your mailbox. Acknowledge once received.

**Comment by binguliki** [comment]
@deepankarvarma yeah sure bro i'll do it for sure

**Comment by deepankarvarma** [comment]
Thank you.
